package question18;

public class Question18_01 {

	public static void main(String[] args)throws TestException {
		// TODO 自動生成されたメソッド・スタブ
		try {
			throw new TestException("独自例外が発生しました。");
		}catch(TestException e) {
			e.printStackTrace();
		}
	}

}
